geo_knowledge_hub/deposit/forms.py
"""Simple deposit form module."""

from __future__ import absolute_import, print_function

from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, FieldList, FormField, Form, validators, HiddenField


render_field = {
    'class': 'form-control'
}


class DocsetForm(Form):
    """Form for document set"""

    docset_doi = StringField(
        'DOI of the Document Set',
        render_kw=render_field
    )
    docset_title = StringField(
        'Title of Document Set',
        render_kw=render_field
    )
    docset_abstract = StringField(
        'Abstract of the Document Set',
        render_kw=render_field
    )
    docset_keywords = FieldList(StringField(
        'Keywords for the Document Set',
        render_kw=render_field
    ), min_entries=2, max_entries=None)
    docset_notes = StringField(
        'Additional notes or comments on the Document Set',
        render_kw=render_field
    )


class PublicationForm(Form):
    """Form for publication"""

    publication_type = StringField(
        'Type of Publication',
    )
    publication_doi = StringField(
        'DOI of the Publication'
    )
    publication_title = StringField(
        'Title of the Publication'
    )
    publication_date = StringField(
        'Date of the Publication'
    )
    publication_authors = FieldList(StringField(
        'Authors of the Publication'
    ), min_entries=3, max_entries=None)
    publication_abstract = StringField(
        'Abstract of the Publication'
    )


class DatasetForm(Form):
    """Form for dataset"""

    dataset_doi = StringField(
        'DOI of the Dataset'
    )
    dataset_creator = StringField(
        'Creator of the Dataset'
    )
    dataset_type = StringField(
        'Type of the Dataset'
    )
    dataset_date = StringField(
        'Date of Dataset'
    )
    dataset_title = StringField(
        'Title of the Dataset'
    )
    dataset_abstract = StringField(
        'Abstract of the Dataset'
    )
    dataset_link = StringField(
        'Link to the Dataset'
    )


class ToolForm(Form):
    """Form for tools"""

    tool_doi = StringField(
        'DOI of the Tool',
        render_kw=render_field
    )
    tool_type = StringField(
        'Type of the Tool',
        render_kw=render_field
    )
    tool_title = StringField(
        'Title of the Tool',
        render_kw=render_field
    )
    tool_abstract = StringField(
        'Abstract of the Tool',
        render_kw=render_field
    )
    tool_link = StringField(
        'Link to the Tool',
        render_kw=render_field
    )


class OutputForm(Form):
    """Form for output & products"""
    output_doi = StringField(
        'DOI of the Output/product',
        render_kw=render_field
    )
    output_type = StringField(
        'Type of the Output/product',
        render_kw=render_field
    )
    output_title = StringField(
        'Title of the Output/product',
        render_kw=render_field
    )
    output_abstract = StringField(
        'Abstract of the Output/product',
        render_kw=render_field
    )
    output_link = StringField(
        'Link to the Output/product',
        render_kw=render_field
    )


class VirtenvForm(Form):
    virtenv_doi = StringField(
        'DOI of the virtual environment',
        render_kw=render_field
    )


class RecordForm(FlaskForm):
    """A simple deposit form."""

    title = StringField(
        'Title', [validators.DataRequired()]
    )
    resource_type = StringField(
        'Type of resource', [validators.DataRequired()]
    )
    # Store bucket identifier containing the uploaded files
    bucket = HiddenField('Bucket', )

    docset = FormField(DocsetForm)
    publications = FieldList(FormField(PublicationForm), min_entries=3, max_entries=None)
    datasets = FieldList(FormField(DatasetForm), min_entries=2, max_entries=None)
    tools = FieldList(FormField(ToolForm), min_entries=1, max_entries=None)
    outputs = FieldList(FormField(OutputForm), min_entries=1, max_entries=None)
    virtenvs = FieldList(FormField(VirtenvForm), min_entries=1, max_entries=None)

geo_knowledge_hub/deposit/__init__.py
"""Deposit module."""

geo_knowledge_hub/deposit/views.py
"""Views for deposit of records."""

from __future__ import absolute_import, print_function

from flask import Blueprint, redirect, render_template, url_for, jsonify, request
from flask_login import login_required
from flask_security import current_user

from invenio_db import db
from invenio_files_rest.models import Bucket, Location, ObjectVersion

from geo_knowledge_hub.config import GEO_KNOWLEDGE_HUB_DEFAULT_BUCKET_URL

from .forms import RecordForm, PublicationForm
from .api import create_record


# define a new Flask Blueprint that is register under the url path /deposit
blueprint = Blueprint(
    'deposit',
    __name__,
    url_prefix='/deposit',
    template_folder='templates',
    static_folder='static',
)


@blueprint.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    """The create view."""
    form = RecordForm()
    # if the form is submitted and valid
    if form.validate_on_submit():
        # create the record
        create_record(
          dict(
            title=form.title.data,
            resource_type=form.resource_type.data,
            docset=form.docset.data,
            publications=form.publications.data,
            datasets=form.datasets.data,
            tools=form.tools.data,
            outputs=form.outputs.data,
            virtenvs=form.virtenvs.data,
            bucket=form.bucket.data
          )
        )
        # redirect to the success page
        return redirect(url_for('deposit.success'))
    return render_template('deposit/create.html', form=form)


@blueprint.route("/success")
@login_required
def success():
    """The success view."""
    return render_template('deposit/success.html')


@blueprint.route('/create-bucket',
                 defaults={'bucket_id': None}, methods=['POST'])
@blueprint.route('/create-bucket/<bucket_id>', methods=['POST'])
def create_bucket(bucket_id=None):
    with db.session.begin_nested():
        loc = Location.get_default()

        if not loc:
            loc = Location(name='local', uri=GEO_KNOWLEDGE_HUB_DEFAULT_BUCKET_URL, default=True)
            db.session.add(loc)

        bucket = None

        if bucket_id:
            bucket = db.session.query(Bucket).filter(Bucket.id == bucket_id).first()

        if not bucket:
            bucket = Bucket.create(
                quota_size=100 * 1000 * 1000,
                max_file_size=100 * 1000 * 1000,
                locked=False
            )

    db.session.commit()

    return jsonify({"bucket_id": bucket.id})


@blueprint.route('/buckets/<bucket_id>', methods=['PUT', 'POST'])
def create_file_in_bucket(bucket_id):
    """
    Route to upload file or files to provided bucket

    Args:
        bucket_id (str): Bucket Identifier

    Returns:
        flask.Response with content serialization as JSON
    """
    files_key = next(request.files.keys())

    for file_storage in request.files.getlist(files_key):
        with db.session.begin_nested():
            bucket = db.session.query(Bucket).filter(Bucket.id == bucket_id).first()

            assert bucket is not None

            ObjectVersion.create(bucket, file_storage.filename, stream=file_storage.stream)
    db.session.commit()

    return jsonify({})


@blueprint.route('/files/<bucket_id>', methods=['DELETE'])
def delete_file(bucket_id):
    key = ''
    deleted_file = ObjectVersion.delete(bucket_id, key)

    if deleted_file:
        return jsonify({"status": "ok"})

    return jsonify({"error": "not found"}), 404


@blueprint.route('/files/<bucket_id>/<key>', methods=['GET'])
def get_bucket_files(bucket_id, key):
    """
    Route to download file from bucket

    Args:
        bucket_id (str): Bucket Identifier
        key (str): File Identifier

    Returns:
        Object Serialization to download
    """

    obj = ObjectVersion.get(bucket_id, key, version_id=1)

    return obj.send_file(restricted=True,
                         as_attachment=False)

geo_knowledge_hub/deposit/templates/deposit/create.html
{%- extends config.BASE_TEMPLATE %}

{%- block css %}
  <!-- Inherit parent CSS -->
  {{ super() }}

  {{ webpack['css_deposit.css'] }}
{%- endblock %}

{%- block javascript %}
  <!-- Inherit parent js -->
  {{ super() }}

  <!-- Geo Knowledge Hub Deposit JS -->
  {{ webpack['js_deposit.js'] }}

{%- endblock javascript %}

{% macro errors(field) %}
  {% if field.errors %}
  <span class="help-block">
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </span>
{% endmacro %}

{% block page_body %}

  <div class="container" ng-app="knowledge_hub.directives">
    <div class="row">

      <form action="{{ url_for('deposit.create') }}"
            method="POST"
            data-bucket-id=""
            enctype="multipart/form-data"
            list-item="{minItems: 1}">

        <!-- sidebar -->
        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <ul class="nav">
            <li>
              <a href="#" ng-click="$ctrl.addItem({ _type: 'publication' })"
                 data-toggle="tooltip" title="Add a new publication"><i class="fa fa-book"></i> Publication</a>
            </li>
            <li>
              <a href="#" data-toggle="tooltip" title="Add a new DataSet"
                 ng-click="$ctrl.addItem({ _type: 'dataset' })"><i class="fa fa-object-group"></i> DataSet</a>
            </li>
            <li>
              <a href="#" data-toggle="tooltip" title="Add a new Tool"
                 ng-click="$ctrl.addItem({ _type: 'tool' })"><i class="fa fa-code-fork"></i> Tool </a>
            </li>
            <li>
              <a href="#" data-toogle="tooltip" title="Add a new Output"
                 ng-click="$ctrl.addItem({ _type: 'output' })">
                <i class="fa fa-briefcase" aria-hidden="true"></i> Output
              </a>
            </li>
            <li>
              <a href="#" data-toggle="tooltip" title="Add a new Virtualenv"
                 ng-click="$ctrl.addItem({ _type: 'virtualenv' })"><i class="fa fa-desktop"></i> Virtualenv </a>
            </li>
          </ul>
        </div>

        <div class="col-xs-12 col-sm-9">
          <h4 class=""><i class="icon-plus-sign-alt"></i>Knowledge Package</h4>

          <hr />

          <div class="form-group ">
              <label for="title">Title</label>
              <input class="form-control" id="title" name="title" required="" type="text" value="">
          </div>

          <div class="form-group">
            <label class="control-label " for="description">Description:</label>
            <textarea placeholder="" class="form-control" id="description" ng-model="$ctrl.item.output_abstract" name="description"></textarea>
          </div>

          <div id="resource_type" class="form-group {{ 'has-error' if form.resource_type.errors }}">
            <label for="resource_type">{{ form.resource_type.label }}</label>
            {{ form.resource_type(class_="form-control")|safe }}
            {{ errors(form.resource_type) }}
          </div>

          {% raw %}
          <div ng-repeat="item in $ctrl.items track by $index">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">
                  <a data-toggle="collapse" href="#panel-record-{{ item.id }}" style="text-transform: capitalize;
"> <span ng-bind="item._type + ' ' + item.id"></span> </a>
                  <button style="position: relative; z-index: 20;" type="button"
                          class="close pull-right"
                          ng-click="$ctrl.removeItem($index)">
                    <span aria-hidden="true">×</span>
                    <span class="sr-only">Close</span>
                  </button>
                </h3>
              </div>
              <div class="panel-body collapse in" id="panel-record-{{ item.id }}" aria-expanded="true">

                <publication id="$index + 1" ng-if="item._type === 'publication'" item="item"></publication>
                <dataset id="$index + 1" ng-if="item._type === 'dataset'" item="item"></dataset>
                <tool id="$index + 1" ng-if="item._type === 'tool'" item="item"></tool>
                <output id="$index + 1" ng-if="item._type === 'output'" item="item"></output>

              </div>
            </div>
          </div>
          {% endraw %}

          {{ form.csrf_token }}
          {{ form.bucket }}

          <button type="submit" class="btn btn-primary pull-right">Save</button>
        </div>

      </form>
    </div>
  </div>

{% endblock page_body %}

geo_knowledge_hub/deposit/templates/deposit/success.html
{%- extends config.BASE_TEMPLATE %}

{% block page_body %}
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="alert alert-success">
          <b>Success!</b>
        </div>
        <a href="{{ url_for('deposit.create') }}" class="btn btn-warning">Create more</a>
      </div>
    </div>
  </div>
{% endblock page_body %}